In [ ]:
#pip install numpy

In [1]:
#import numpy
import numpy as np

In [ ]:
# Creating an array using numpy

In [2]:
food= np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
prices =np.array([5,5,5])
prices

array([5, 5, 5])

In [5]:
type(prices)

numpy.ndarray

In [6]:
type(food)

numpy.ndarray

In [7]:
len(food)

3

In [8]:
len(prices)

3

In [10]:
prices[0:]

array([5, 5, 5])

In [11]:
food[1]

'samosa'

In [14]:
prices.mean()

5.0

In [16]:
#zerors
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
prices[0:]

array([5, 5, 5])

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
#empty
np.empty(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#specify
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
#interrval
np.arange(5,55, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [44]:
#line space
np.linspace(1, 100, num=200)

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

In [46]:
#specify Data type

np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [47]:
# with flot
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

# Array Functions

In [51]:
# automatic convert integer in float
a=np.array([12, 1, 115,105, 125.8, 137.90])
a

array([ 12. ,   1. , 115. , 105. , 125.8, 137.9])

In [52]:
#sort the arrary
a.sort()
a

array([  1. ,  12. , 105. , 115. , 125.8, 137.9])

In [66]:
#Concatenate Arrays
b=np.array([3,5,9,19,3.5,1,17,3])
b
c= np.concatenate((a,b))
c

array([  1. ,  12. , 105. , 115. , 125.8, 137.9,   3. ,   5. ,   9. ,
        19. ,   3.5,   1. ,  17. ,   3. ])

In [67]:
#sort with variable
c.sort()
c

array([  1. ,   1. ,   3. ,   3. ,   3.5,   5. ,   9. ,  12. ,  17. ,
        19. , 105. , 115. , 125.8, 137.9])

# 2-D Arrays

In [104]:
a=np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [71]:
b=np.array([[6,7,8,9,10],[10,9,8,7,6]])
b

array([[ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [73]:
# Concatenate 2-D Arrays
# same length array donot require demissions argument because defualt is axis=0
c = np. concatenate((a,b))
c

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [74]:
# concatenate all data array one and then array two same order
c = np. concatenate((a,b), axis=0)
c

array([[ 1,  2,  3,  4,  5],
       [ 5,  4,  3,  2,  1],
       [ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [75]:
# join first row of a with first row of b and vise versa
c = np. concatenate((a,b), axis=1)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6]])

In [88]:
# 3 dimention array with order of two two arrays
d = np.array([
    [[0,1,2],[2,1,0]],
            [[3,4,5],[5,4,3]],
    
             [[6,7,8],[8,7,6]]
])
d

array([[[0, 1, 2],
        [2, 1, 0]],

       [[3, 4, 5],
        [5, 4, 3]],

       [[6, 7, 8],
        [8, 7, 6]]])

In [89]:
# to find dimention number
d.ndim

3

In [93]:
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [94]:
b

array([[ 6,  7,  8,  9, 10],
       [10,  9,  8,  7,  6]])

In [95]:
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  4,  3,  2,  1, 10,  9,  8,  7,  6]])

In [96]:
d

array([[[0, 1, 2],
        [2, 1, 0]],

       [[3, 4, 5],
        [5, 4, 3]],

       [[6, 7, 8],
        [8, 7, 6]]])

In [99]:
a.ndim

2

In [100]:
d.ndim

3

In [101]:
a.size # number of elements

10

In [102]:
a.shape   # Rows and Column of array

(2, 5)

In [106]:
d.shape # result indicate that 3layers, 2 Rows and 3 colomns

(3, 2, 3)

In [136]:
#reshape change the order
a=np.array([[7,8,9,10,11,12,1,2,3,4,5,6]])
a
np.shape(a)

(1, 12)

In [128]:
a.size

12

In [135]:
a.reshape(1,2,6b
np.sort(a)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [122]:
a.ndarray.sort

AttributeError: 'numpy.ndarray' object has no attribute 'ndarray'

In [145]:
# 1-D array converts to 2.D array
a.shape
b =a. reshape(2,6)
b.ndim

2

In [150]:
# 1-D array convert to 3-D array with with 2 layers  2 rows and 3 columns
c = a.reshape(2,2,3)
c.ndim

3

In [153]:
# 1-D array convert to 3-D array with with 3 layers  2 rows and 3 columns

c = a.reshape(3,2,2)
c

array([[[ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [ 1,  2]],

       [[ 3,  4],
        [ 5,  6]]])

In [163]:
#column wise New axis
a = np.array([1,2,3,4,5,6])
d = a[:, np.newaxis]
d

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [164]:
#Row wise New axis
a = np.array([1,2,3,4,5,6])
d = a[np.newaxis, :]
d

array([[1, 2, 3, 4, 5, 6]])

In [165]:
#slicing function
a[2:6]
a

array([1, 2, 3, 4, 5, 6])

In [166]:
#multiply *6
a*6

array([ 6, 12, 18, 24, 30, 36])

In [167]:
#sum
a.sum()

21

In [168]:
#mean
a.mean()

3.5

In [169]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [170]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [172]:
a[a<=5]

array([1, 2, 3, 4, 5])

In [173]:
#slicing within rang
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
#two conditions using the & and | operators
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [179]:
#use of the logical operators & and | in order to return boolean values 
five_up = (a > 5) | (a == 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [184]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

In [185]:
#virtical joining
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [186]:
#Horizontal joinig
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [190]:
#make array 0-24
x = np.arange(1, 25)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [193]:
#reshap array 
x=x.reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [194]:
#hsplit -- split into 3 equalparts
x = np.arange(1, 25)
np.hsplit(x,3)

[array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24])]

In [196]:
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [208]:
#assign array a ki 2 row four elements
b1 = a[2, :]
b1

array([99, 10, 11, 12])

In [209]:
#change 0 position element with 99
b1[0]=99
b1

array([99, 10, 11, 12])

In [207]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [99, 10, 11, 12]])

In [211]:
# copy array
b2 = a.copy()
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [99, 10, 11, 12]])

In [212]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [217]:
# first row 2nd element
data[0, 1]

2

In [218]:
#first row 2nd element
data[1, 1]

4

In [229]:
# second row 4 element
data[1:3]

array([[3, 4],
       [5, 6]])

In [232]:
data[2:1]

array([], shape=(0, 2), dtype=int32)

## Reshaping and flattening multidimensional arrays

In [233]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [235]:
#flatten not change orginal array 
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [236]:
# change in parent array
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [245]:
#find in array  return postion of find value
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)


(array([3, 5, 6], dtype=int64),)
